### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by joprice** [jrudolph/sbt-optimizer#4]
Has this been published? If so, is there another resolver required?

**Comment by jrudolph** [comment]
Nope, it's not yet released :) But you should be able to `publish-local`.

**Comment by jrudolph** [comment]
Let's repurpose this ticket to make an actual release.

**Comment by joprice** [comment]
Yea need to get it past the bootstrapping stage. I just tried to publishLocal and noticed it's referencing itself in build.sbt :-)

**Comment by joprice** [comment]
Just tried it. Its beautiful. It could use some headers though. Also, the task name is a bit cut off. Perhaps the visualization could be resized instead of the task name being truncated. 
<img width="976" alt="screen shot 2016-01-18 at 5 44 44 pm" src="https://cloud.githubusercontent.com/assets/2175555/12404646/4eb53246-be0b-11e5-813c-32dc86e120e0.png">

**Comment by jrudolph** [comment]
I agree, I created #5 to make it configurable.
